[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/src/janatics_part_number_generator_all_products.html"
  status = 200

[[redirects]]
  from = "/janatics"
  to = "/src/janatics_part_number_generator_all_products.html"
  status = 200

[[redirects]]
  from = "/dealer"
  to = "/src/janatics_part_number_generator_all_products.html"
  status = 200
